#!/usr/bin/env python3
"""
Hydrofoil SDF Generator
Run this script to generate the model.sdf file with updated physical parameters.
"""

import os

# ==========================================
# 1. PARAMETERS
# ==========================================

# --- BOARD ---
BOARD_LENGTH = 1.8
BOARD_WIDTH = 0.5
BOARD_THICKNESS = 0.15
BOARD_MASS = 50.0  # kg

# --- MAST ---
MAST_LENGTH = 0.8  # Vertical height
MAST_WIDTH = 0.12
MAST_THICKNESS = 0.02
MAST_MASS = 4.0    # kg
MAST_X_OFFSET = -0.2 # Position relative to board center
MAST_Z_OFFSET = - (BOARD_THICKNESS/2.0 + MAST_LENGTH/2.0)

# --- MAIN FOIL (WINGS) ---
MAIN_FOIL_SPAN = 0.8 # y-axis
MAIN_FOIL_CHORD = 0.15 # x-axis
MAIN_FOIL_THICKNESS = 0.02 # z-axis
MAIN_FOIL_MASS = 2.0 # kg
MAIN_FOIL_Z_OFFSET = MAST_Z_OFFSET - (MAST_LENGTH/2.0)

# --- ELEVATOR (PITCH WING) ---
ELEVATOR_SPAN = 0.4
ELEVATOR_CHORD = 0.08
ELEVATOR_THICKNESS = 0.01
ELEVATOR_MASS = 0.5  # kg
ELEVATOR_X_OFFSET = MAST_X_OFFSET - 0.4 # Distance behind mast
ELEVATOR_Z_OFFSET = MAIN_FOIL_Z_OFFSET

# --- RUDDER (YAW WING) ---
RUDDER_SPAN = 0.08 # y-axis width
RUDDER_CHORD = 0.08 # x-axis length
RUDDER_HEIGHT = 0.3 # z-axis height
RUDDER_MASS = 0.5    # kg
RUDDER_X_OFFSET = ELEVATOR_X_OFFSET - 0.05
RUDDER_Z_OFFSET = ELEVATOR_Z_OFFSET + (RUDDER_HEIGHT/2.0)

# --- PROPULSION ---
PROP_X_OFFSET = MAST_X_OFFSET - 0.3
PROP_Z_OFFSET = MAIN_FOIL_Z_OFFSET
MAX_THRUST_RPM = 3500

# ==========================================
# 2. INERTIA CALCULATOR
# ==========================================

def calc_box_inertia(mass, x, y, z):
    """Calculates moment of inertia for a box"""
    ixx = (1.0 / 12.0) * mass * (y**2 + z**2)
    iyy = (1.0 / 12.0) * mass * (x**2 + z**2)
    izz = (1.0 / 12.0) * mass * (x**2 + y**2)
    return ixx, iyy, izz

b_ixx, b_iyy, b_izz = calc_box_inertia(BOARD_MASS, BOARD_LENGTH, BOARD_WIDTH, BOARD_THICKNESS)
m_ixx, m_iyy, m_izz = calc_box_inertia(MAST_MASS, MAST_CHORD:=MAST_WIDTH, MAST_SPAN:=MAST_THICKNESS, MAST_LENGTH)
mf_ixx, mf_iyy, mf_izz = calc_box_inertia(MAIN_FOIL_MASS, MAIN_FOIL_CHORD, MAIN_FOIL_SPAN, MAIN_FOIL_THICKNESS)
e_ixx, e_iyy, e_izz = calc_box_inertia(ELEVATOR_MASS, ELEVATOR_CHORD, ELEVATOR_SPAN, ELEVATOR_THICKNESS)
r_ixx, r_iyy, r_izz = calc_box_inertia(RUDDER_MASS, RUDDER_CHORD, RUDDER_SPAN, RUDDER_HEIGHT)

# ==========================================
# 3. SDF TEMPLATE
# ==========================================

sdf_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT MANUALLY. Generated by generate_model.py -->
<sdf version='1.9'>
  <model name='hf'>
    <pose>0 0 0.5 0 0 0</pose>
    
    <!-- ======================= -->
    <!-- 1. MAIN BOARD           -->
    <!-- ======================= -->
    <link name='base_link'>
      <pose>0 0 0 0 0 0</pose>
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>{BOARD_MASS}</mass>
        <inertia>
          <ixx>{b_ixx:.5f}</ixx><ixy>0</ixy><ixz>0</ixz>
          <iyy>{b_iyy:.5f}</iyy><iyz>0</iyz>
          <izz>{b_izz:.5f}</izz>
        </inertia>
      </inertial>
      
      <collision name='base_link_collision'>
        <geometry>
          <box><size>{BOARD_LENGTH} {BOARD_WIDTH} {BOARD_THICKNESS}</size></box>
        </geometry>
      </collision>
      <visual name='base_link_visual'>
        <geometry>
          <box><size>{BOARD_LENGTH} {BOARD_WIDTH} {BOARD_THICKNESS}</size></box>
        </geometry>
        <material>
          <ambient>0.2 0.2 0.2 1</ambient>
          <diffuse>0.8 0.1 0.1 1</diffuse>
        </material>
      </visual>

      <!-- Sensors -->
      <sensor name="imu_sensor" type="imu"><gz_frame_id>base_link</gz_frame_id><always_on>1</always_on><update_rate>250</update_rate></sensor>
      <sensor name="air_pressure_sensor" type="air_pressure"><gz_frame_id>base_link</gz_frame_id><always_on>1</always_on><update_rate>50</update_rate></sensor>
      <sensor name="magnetometer_sensor" type="magnetometer"><gz_frame_id>base_link</gz_frame_id><always_on>1</always_on><update_rate>100</update_rate></sensor>
      <sensor name="navsat_sensor" type="navsat"><gz_frame_id>base_link</gz_frame_id><always_on>1</always_on><update_rate>30</update_rate></sensor>
    </link>

    <plugin filename="gz-sim-buoyancy-system" name="gz::sim::systems::Buoyancy">
      <graded_buoyancy>
        <default_density>997</default_density>
        <density_profile><depth>0</depth><density>997</density></density_profile>
      </graded_buoyancy>
      <link_name>base_link</link_name>
    </plugin>
    <plugin filename="gz-sim-hydrodynamics-system" name="gz::sim::systems::Hydrodynamics">
      <link_name>base_link</link_name>
      <xU>-15.0</xU><yV>-30.0</yV><zW>-100.0</zW>
      <kP>-10.0</kP><mQ>-20.0</mQ><nR>-15.0</nR>
      <xUabsU>-20.0</xUabsU><yVabsV>-50.0</yVabsV><zWabsW>-150.0</zWabsW>
    </plugin>

    <!-- ======================= -->
    <!-- 2. MAST                 -->
    <!-- ======================= -->
    <link name='mast_link'>
      <pose>{MAST_X_OFFSET} 0 {MAST_Z_OFFSET} 0 0 0</pose>
      <inertial>
        <mass>{MAST_MASS}</mass>
        <inertia>
          <ixx>{m_ixx:.5f}</ixx><iyy>{m_iyy:.5f}</iyy><izz>{m_izz:.5f}</izz>
        </inertia>
      </inertial>
      <visual name='mast_visual'>
        <geometry><box><size>{MAST_CHORD} {MAST_SPAN} {MAST_LENGTH}</size></box></geometry>
        <material><ambient>0.5 0.5 0.5 1</ambient></material>
      </visual>
      <collision name='mast_collision'>
        <geometry><box><size>{MAST_CHORD} {MAST_SPAN} {MAST_LENGTH}</size></box></geometry>
      </collision>
    </link>
    <joint name='mast_joint' type='fixed'>
      <parent>base_link</parent>
      <child>mast_link</child>
    </joint>

    <!-- ======================= -->
    <!-- 3. MAIN FOIL            -->
    <!-- ======================= -->
    <link name="main_foil">
      <pose>{MAST_X_OFFSET} 0 {MAIN_FOIL_Z_OFFSET} 0 0 0</pose>
      <inertial>
        <mass>{MAIN_FOIL_MASS}</mass>
        <inertia>
          <ixx>{mf_ixx:.5f}</ixx><iyy>{mf_iyy:.5f}</iyy><izz>{mf_izz:.5f}</izz>
        </inertia>
      </inertial>
      <visual name='main_foil_visual'>
        <geometry><box><size>{MAIN_FOIL_CHORD} {MAIN_FOIL_SPAN} {MAIN_FOIL_THICKNESS}</size></box></geometry>
      </visual>
      <collision name='main_foil_collision'>
        <geometry><box><size>{MAIN_FOIL_CHORD} {MAIN_FOIL_SPAN} {MAIN_FOIL_THICKNESS}</size></box></geometry>
      </collision>
    </link>
    <joint name="main_foil_joint" type="fixed">
      <parent>mast_link</parent>
      <child>main_foil</child>
    </joint>
    <plugin filename="gz-sim-advanced-lift-drag-system" name="gz::sim::systems::AdvancedLiftDrag">
      <a0>0.0</a0><CL0>0.15</CL0><AR>6.0</AR><eff>0.97</eff><CLa>5.0</CLa><CD0>0.03</CD0><Cema>-0.4</Cema>
      <alpha_stall>0.3</alpha_stall><CLa_stall>-3.8</CLa_stall><CDa_stall>-0.9</CDa_stall>
      <area>{MAIN_FOIL_CHORD * MAIN_FOIL_SPAN}</area>
      <mac>{MAIN_FOIL_CHORD}</mac>
      <air_density>997.0</air_density>
      <forward>1 0 0</forward><upward>0 0 1</upward>
      <link_name>main_foil</link_name>
    </plugin>

    <!-- ======================= -->
    <!-- 4. ELEVATOR (PITCH)     -->
    <!-- ======================= -->
    <link name="elevator">
      <pose>{ELEVATOR_X_OFFSET} 0 {ELEVATOR_Z_OFFSET} 0 0 0</pose>
      <inertial>
        <mass>{ELEVATOR_MASS}</mass>
        <inertia>
          <ixx>{e_ixx:.5f}</ixx><iyy>{e_iyy:.5f}</iyy><izz>{e_izz:.5f}</izz>
        </inertia>
      </inertial>
      <visual name='elevator_visual'>
        <geometry><box><size>{ELEVATOR_CHORD} {ELEVATOR_SPAN} {ELEVATOR_THICKNESS}</size></box></geometry>
      </visual>
      <collision name='elevator_collision'>
        <geometry><box><size>{ELEVATOR_CHORD} {ELEVATOR_SPAN} {ELEVATOR_THICKNESS}</size></box></geometry>
      </collision>
    </link>
    <joint name='servo_0' type='revolute'>
      <parent>base_link</parent>
      <child>elevator</child>
      <pose>0 0 0 0 0 0</pose>
      <axis><xyz>0 1 0</xyz><limit><lower>-0.78</lower><upper>0.78</upper></limit></axis>
    </joint>
    <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
      <joint_name>servo_0</joint_name><sub_topic>servo_0</sub_topic>
      <p_gain>10</p_gain><i_gain>0</i_gain><d_gain>0</d_gain>
    </plugin>
    <plugin filename="gz-sim-advanced-lift-drag-system" name="gz::sim::systems::AdvancedLiftDrag">
      <a0>0.0</a0><CL0>0.0</CL0><AR>5.0</AR><eff>0.97</eff><CLa>5.0</CLa><CD0>0.02</CD0><Cema>-0.4</Cema>
      <alpha_stall>0.3</alpha_stall><CLa_stall>-3.8</CLa_stall><CDa_stall>-0.9</CDa_stall>
      <area>{ELEVATOR_CHORD * ELEVATOR_SPAN}</area>
      <mac>{ELEVATOR_CHORD}</mac>
      <air_density>997.0</air_density>
      <forward>1 0 0</forward><upward>0 0 1</upward>
      <link_name>elevator</link_name>
      <num_ctrl_surfaces>1</num_ctrl_surfaces>
      <control_surface>
        <name>servo_0</name><index>0</index><direction>-1</direction>
        <CD_ctrl>0.0002</CD_ctrl><CY_ctrl>0</CY_ctrl><CL_ctrl>0.01</CL_ctrl>
        <Cell_ctrl>0.0</Cell_ctrl><Cem_ctrl>-0.02</Cem_ctrl><Cen_ctrl>0.0</Cen_ctrl>
      </control_surface>
    </plugin>

    <!-- ======================= -->
    <!-- 5. RUDDER (YAW)         -->
    <!-- ======================= -->
    <link name="rudder">
      <pose>{RUDDER_X_OFFSET} 0 {RUDDER_Z_OFFSET} 0 0 0</pose>
      <inertial>
        <mass>{RUDDER_MASS}</mass>
        <inertia>
          <ixx>{r_ixx:.5f}</ixx><iyy>{r_iyy:.5f}</iyy><izz>{r_izz:.5f}</izz>
        </inertia>
      </inertial>
      <visual name='rudder_visual'>
        <geometry><box><size>{RUDDER_CHORD} {RUDDER_SPAN} {RUDDER_HEIGHT}</size></box></geometry>
      </visual>
      <collision name='rudder_collision'>
        <geometry><box><size>{RUDDER_CHORD} {RUDDER_SPAN} {RUDDER_HEIGHT}</size></box></geometry>
      </collision>
    </link>
    <joint name='servo_1' type='revolute'>
      <parent>base_link</parent>
      <child>rudder</child>
      <pose>0 0 0 0 0 0</pose>
      <axis><xyz>0 0 1</xyz><limit><lower>-0.78</lower><upper>0.78</upper></limit></axis>
    </joint>
    <plugin filename="gz-sim-joint-position-controller-system" name="gz::sim::systems::JointPositionController">
      <joint_name>servo_1</joint_name><sub_topic>servo_1</sub_topic>
      <p_gain>10</p_gain><i_gain>0</i_gain><d_gain>0</d_gain>
    </plugin>
    <plugin filename="gz-sim-advanced-lift-drag-system" name="gz::sim::systems::AdvancedLiftDrag">
      <a0>0.0</a0><CL0>0.0</CL0><AR>3.75</AR><eff>0.97</eff><CLa>5.0</CLa><CD0>0.02</CD0><Cema>-0.4</Cema>
      <alpha_stall>0.3</alpha_stall><CLa_stall>-3.8</CLa_stall><CDa_stall>-0.9</CDa_stall>
      <area>{RUDDER_CHORD * RUDDER_HEIGHT}</area>
      <mac>{RUDDER_CHORD}</mac>
      <air_density>997.0</air_density>
      <forward>1 0 0</forward><upward>0 1 0</upward> <!-- Note: Upward is Y because rudder is vertical -->
      <link_name>rudder</link_name>
      <num_ctrl_surfaces>1</num_ctrl_surfaces>
      <control_surface>
        <name>servo_1</name><index>0</index><direction>1</direction>
        <CD_ctrl>0.0002</CD_ctrl><CY_ctrl>-0.01</CY_ctrl><CL_ctrl>0.0</CL_ctrl>
        <Cell_ctrl>0.0</Cell_ctrl><Cem_ctrl>0.0</Cem_ctrl><Cen_ctrl>0.02</Cen_ctrl>
      </control_surface>
    </plugin>

    <!-- ======================= -->
    <!-- 6. ENGINE (THRUSTER)    -->
    <!-- ======================= -->
    <link name='rotor_puller'>
      <pose>{PROP_X_OFFSET} 0 {PROP_Z_OFFSET} 0 1.57 0</pose>
      <inertial>
        <mass>0.5</mass>
        <inertia><ixx>1e-04</ixx><iyy>1e-04</iyy><izz>1e-04</izz></inertia>
      </inertial>
      <visual name='rotor_puller_visual'>
        <geometry><cylinder><length>0.05</length><radius>0.15</radius></cylinder></geometry>
      </visual>
    </link>
    <joint name='rotor_puller_joint' type='revolute'>
      <child>rotor_puller</child>
      <parent>base_link</parent>
      <axis><xyz>1 0 0</xyz><limit><lower>-1e+16</lower><upper>1e+16</upper></limit></axis>
    </joint>
    <plugin filename="gz-sim-multicopter-motor-model-system" name="gz::sim::systems::MulticopterMotorModel">
      <jointName>rotor_puller_joint</jointName>
      <linkName>rotor_puller</linkName>
      <turningDirection>cw</turningDirection>
      <timeConstantUp>0.0125</timeConstantUp>
      <timeConstantDown>0.025</timeConstantDown>
      <maxRotVelocity>{MAX_THRUST_RPM}</maxRotVelocity>
      <motorConstant>8.54858e-05</motorConstant> <!-- Increased for more thrust in water -->
      <momentConstant>0.01</momentConstant>
      <commandSubTopic>command/motor_speed</commandSubTopic>
      <motorNumber>0</motorNumber>
      <rotorDragCoefficient>8.06428e-05</rotorDragCoefficient>
      <rollingMomentCoefficient>1e-06</rollingMomentCoefficient>
      <rotorVelocitySlowdownSim>10</rotorVelocitySlowdownSim>
      <motorType>velocity</motorType>
    </plugin>

    <!-- ======================= -->
    <!-- 7. LIDAR SENSOR (LW20)  -->
    <!-- ======================= -->
    <include merge='true'>
      <uri>model://LW20</uri>
      <pose relative_to="base_link">{BOARD_LENGTH/2.0 - 0.1} 0 -0.079 0 1.57 0</pose>
    </include>
    <joint name="lidar_model_joint" type="fixed">
      <parent>base_link</parent>
      <child>lw20_link</child>
    </joint>
    <joint name="lidar_sensor_joint" type="fixed">
      <parent>base_link</parent>
      <child>lidar_sensor_link</child>
    </joint>
    <link name="lidar_sensor_link">
      <pose relative_to="base_link">{BOARD_LENGTH/2.0 - 0.1} 0 -0.05 0 1.57 0</pose>
      <inertial>
        <mass>0.001</mass>
        <inertia><ixx>0.00001</ixx><iyy>0.00001</iyy><izz>0.00001</izz></inertia>
      </inertial>
      <sensor name='lidar' type='gpu_lidar'>
        <pose>0 0 0 3.14 0 0</pose>
        <update_rate>50</update_rate>
        <ray>
          <scan>
            <horizontal><samples>1</samples><resolution>1</resolution><min_angle>0</min_angle><max_angle>0</max_angle></horizontal>
            <vertical><samples>1</samples><resolution>1</resolution><min_angle>0</min_angle><max_angle>0</max_angle></vertical>
          </scan>
          <range><min>0.1</min><max>100.0</max><resolution>0.01</resolution></range>
        </ray>
        <always_on>1</always_on>
        <visualize>true</visualize>
      </sensor>
    </link>

  </model>
</sdf>
"""

if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, "model.sdf")
    
    with open(output_path, "w") as f:
        f.write(sdf_content)
        
    print(f"Successfully generated {output_path} with updated parameters!")
